### ISSUE TITLE
arkaos-remoteplayer

### ISSUE THREAD

**Issue by michaelarkaos** [bitfocus/companion-module-arkaos-mediamaster#1]
Hi, 
I am the web developer of Arkaos company and I would like to create our custom module for the new version of Mediamaster software.
https://pro.arkaos.com

Kind Regards

- Michaël

**Comment by michaelarkaos** [comment]
Hi Joseph, The module is ready and tested with our software. I have also pushed all changes. 
I have also created a request in #module-development on slack, and give @krocheck a tag ...
I will wait for the validation. Thanks for your help.

**Comment by michaelarkaos** [comment]
Hi @josephdadams @krocheck, i have requested in #module-development on slack, and I received no answer ?
Could you check and validate the arkaos-remoteplayer module ?

**Comment by michaelarkaos** [comment]
Hi @josephdadams @krocheck, i have no news about our companion module arkaos-remoteplayer ? there is an issue ?
We would like to launch new software in September and would like that the module also be ready..

**Comment by josephdadams** [comment]
v1.0.5 in betas now
